import { classifyNftTaste, NormalizedNft } from "../lib/jpgs/classifyNftTaste";
import { TASTE_CATEGORY_LABELS } from "../lib/jpgs/tasteCategories";

// ─── Test fixtures ────────────────────────────────────────────────────────────

const testNfts: { label: string; nft: NormalizedNft }[] = [
  {
    label: "1. Generative art — Chromie Squiggle",
    nft: {
      name: "Chromie Squiggle #4512",
      collectionName: "Chromie Squiggle by Snowfro",
      collectionSlug: "chromie-squiggle-by-snowfro",
      collectionDescription:
        "A simple and elegant on-chain generative art project. Each squiggle is uniquely generated by an algorithm written in Solidity.",
      tokenStandard: "ERC721",
      animationUrl: "https://generator.artblocks.io/0x059edd72cd353df5106d2b9cc5ab83a52287ac3a/4512",
      traits: [
        { trait_type: "Palette", value: "Sizzle" },
        { trait_type: "Spectrum", value: "Full" },
        { trait_type: "Steps", value: 24 },
        { trait_type: "Algorithm", value: "Standard" },
      ],
    },
  },
  {
    label: "2. PFP / Identity — Pudgy Penguin",
    nft: {
      name: "Pudgy Penguin #1337",
      collectionName: "Pudgy Penguins",
      collectionSlug: "pudgy-penguins",
      collectionDescription:
        "Pudgy Penguins is a collection of 8,888 NFTs. Community-driven PFP avatars living on the Ethereum blockchain.",
      tokenStandard: "ERC721",
      traits: [
        { trait_type: "Background", value: "Dark Grey" },
        { trait_type: "Skin", value: "Normal" },
        { trait_type: "Eyes", value: "Glasses" },
        { trait_type: "Head", value: "Beanie" },
        { trait_type: "Body", value: "Sailor Outfit" },
        { trait_type: "Mouth", value: "Happy" },
      ],
    },
  },
  {
    label: "3. Meme / Internet Culture — The Memes by 6529",
    nft: {
      name: "Sgt. Pepe #164",
      collectionName: "The Memes by 6529",
      collectionSlug: "the-memes-by-6529",
      collectionDescription:
        "The Memes is a collection of NFTs created by 6529 Collections to educate and inspire about open metaverse values. Meme cards celebrating crypto-native internet culture.",
      tokenStandard: "ERC1155",
      traits: [
        { trait_type: "Meme Name", value: "Sgt. Pepe" },
        { trait_type: "Punk 6529", value: "Yes" },
        { trait_type: "Season", value: "1" },
        { trait_type: "Card Number", value: 164 },
      ],
    },
  },
  {
    label: "4. Access / Membership — Storyverse Founders Pass",
    nft: {
      name: "Storyverse Founders Pass #021",
      collectionName: "Storyverse Founders Pass",
      collectionSlug: "storyverse-founders-pass",
      collectionDescription:
        "Storyverse Founders Pass grants holders exclusive membership access to Storyverse community events, token-gated content, and founder credentials.",
      tokenStandard: "ERC721",
      traits: [
        { trait_type: "Tier", value: "Founder" },
        { trait_type: "Access", value: "Full" },
        { trait_type: "Membership", value: "Lifetime" },
      ],
    },
  },
  {
    label: "5. Gaming / Worlds — DungeonRooms",
    nft: {
      name: "Dungeon Room #0441",
      collectionName: "DungeonRooms",
      collectionSlug: "dungeonrooms",
      collectionDescription:
        "DungeonRooms are on-chain playable virtual dungeon rooms. Each room is a unique world object that exists inside the dungeon metaverse.",
      tokenStandard: "ERC721",
      traits: [
        { trait_type: "World", value: "Dungeon" },
        { trait_type: "Room", value: "Armory" },
        { trait_type: "Level", value: 3 },
        { trait_type: "Item", value: "Sword" },
      ],
    },
  },
];

// ─── Runner ───────────────────────────────────────────────────────────────────

function pct(n: number | undefined): string {
  return n !== undefined ? `${Math.round(n * 100)}%` : "—";
}

function label(cat: string): string {
  return TASTE_CATEGORY_LABELS[cat as keyof typeof TASTE_CATEGORY_LABELS] ?? cat;
}

for (const { label: title, nft } of testNfts) {
  const result = classifyNftTaste(nft);

  const topEvidence = [...result.evidence]
    .sort((a, b) => b.weight - a.weight)
    .slice(0, 4);

  const confidenceLines = (Object.entries(result.confidence) as [string, number][])
    .sort(([, a], [, b]) => b - a)
    .map(([cat, c]) => `    ${label(cat).padEnd(28)} ${pct(c)}`)
    .join("\n");

  console.log(`\n${"─".repeat(60)}`);
  console.log(`${title}`);
  console.log(`${"─".repeat(60)}`);
  console.log(`  NFT name          : ${nft.name}`);
  console.log(`  Primary category  : ${label(result.primaryCategory)}`);
  console.log(
    `  Secondary         : ${result.secondaryCategories.map(label).join(", ") || "(none)"}`
  );
  console.log(`  Tags              : ${result.tags.join(", ") || "(none)"}`);
  console.log(`  Confidence scores :`);
  console.log(confidenceLines);
  console.log(`  Top evidence      :`);
  for (const e of topEvidence) {
    console.log(
      `    [${e.source}] ${e.field} → "${e.value}"  →  ${label(e.category)}  (w=${e.weight})`
    );
  }
}

console.log(`\n${"─".repeat(60)}`);
console.log(`All ${testNfts.length} classifier tests complete.`);
console.log(`${"─".repeat(60)}\n`);
